[package]
name = "summarymd"
version = "0.1.2"
edition = "2024"
description = "dump a codebase to a markdown file"
license = "GPL-3.0-or-later"
repository = "https://github.com/andtsa/summary"
homepage = "https://github.com/andtsa/summary"
readme = "README.md"
keywords = ["cli", "codebase", "codebase-to-text"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1"
clap = { version = "4.6.0", features = ["derive"] }
clio = { version = "0.3.5", features = ["clap-parse"] }
glob = "0.3.3"
regex-lite = "0.1.9"
serde = "1"
serde_derive = "1"
toml = "1"
walkdir = "2.5.0"
